name: photofilters
description: A flutter package for applying various types of filters to an image. You can create your own filters and subfilters too.
version: 1.0.3
author: Sharafudheen KK <skkallayath@gmail.com>
homepage: https://github.com/skkallayath/photofilters

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.9
  meta: ^1.1.8
  path_provider: ^1.5.1

  #widgets
  flutter_platform_widgets: 0.30.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test:
  image_picker:
  path:

flutter:
